In [2]:
!unzip ./GloVe/Glove_2gb/glove.840B.300d.zip -d ./GloVe/Glove_2gb/

Archive:  ./GloVe/Glove_2gb/glove.840B.300d.zip
  inflating: ./GloVe/Glove_2gb/glove.840B.300d.txt  


In [2]:
import numpy as np

def load_glove_embeddings(file_path):
    embeddings = {}
    with open(file_path, 'r', encoding='utf-8') as file:
        for line in file:
            values = line.split()
            word = values[0]
            vector = np.asarray(values[1:], dtype='float32')
            embeddings[word] = vector
    return embeddings

glove_embeddings_100 = load_glove_embeddings('./GloVe/glove.6B.100d.txt')

In [3]:
word = 'example'
word_vector = glove_embeddings_100[word]

In [4]:
word_vector

array([-0.12617  ,  0.61724  ,  0.22581  ,  0.39868  ,  0.16111  ,
        0.1523   , -0.14715  , -0.29447  , -0.27348  , -0.13753  ,
       -0.20898  , -0.73436  ,  0.14144  ,  0.15048  ,  0.09179  ,
        0.018613 ,  0.22539  ,  0.15979  , -0.16935  ,  0.42716  ,
        0.042284 , -0.3477   , -0.11413  ,  0.12222  , -0.025027 ,
       -0.20805  , -0.067264 , -0.2956   , -0.30807  , -0.32903  ,
        0.19059  ,  0.77141  , -0.19332  , -0.31069  ,  0.26745  ,
        0.32231  ,  0.2065   ,  0.10497  ,  0.49425  , -0.38322  ,
       -0.12802  , -0.069906 , -0.14828  ,  0.085369 , -0.18141  ,
        0.14688  ,  0.60968  , -0.21131  , -0.29148  , -0.52773  ,
        0.59508  ,  0.017369 ,  0.15342  ,  0.81925  , -0.20643  ,
       -2.0378   , -0.11884  , -0.16826  ,  1.5288   ,  0.15756  ,
       -0.4994   ,  0.39305  ,  0.12672  , -0.10968  ,  1.3671   ,
       -0.21006  ,  0.15684  ,  0.0063801,  0.43836  , -0.18765  ,
       -0.29088  ,  0.18619  ,  0.085402 ,  0.13985  ,  0.4079

In [5]:
def vectorize_preprocessed_text(tokens, embeddings, embedding_dim=100):
    text_vector = np.zeros(embedding_dim)
    n_tokens = 0
    for token in tokens:
        if token in embeddings:
            text_vector += embeddings[token]
            n_tokens += 1
    if n_tokens > 0:
        text_vector /= n_tokens
    return text_vector

# Example usage:
review = ['this', 'is', 'an', 'example', 'review']
vectorize_preprocessed_text(review, glove_embeddings_100)


array([-4.81961992e-01,  2.17246002e-01,  5.34089997e-01, -1.61714002e-01,
        1.34598604e-01,  9.28380024e-02, -6.51241958e-02,  3.09910002e-01,
       -1.80134398e-01,  7.02617973e-02, -7.05535986e-02, -2.96088795e-01,
        1.51007001e-01, -1.58088000e-01, -2.43440457e-03,  3.63582002e-02,
        3.83175201e-01, -2.04482011e-02, -1.74594003e-01,  3.30640797e-01,
        1.37514805e-01, -2.91508007e-01,  9.34019834e-03,  1.28722000e-01,
        3.64557607e-01, -8.44298817e-02,  8.71437997e-02, -4.30402005e-01,
       -2.50883599e-01, -4.86235999e-02, -3.04498200e-01,  6.22098591e-01,
       -2.49679975e-02,  7.39772044e-02, -2.74420053e-02,  2.68555801e-01,
        1.09224396e-01,  2.38301991e-01,  3.67670026e-02, -2.36533996e-01,
       -4.86095986e-01,  1.05131403e-01,  7.25842036e-02, -2.55198994e-01,
        7.93462038e-02, -1.22662203e-01,  4.16725993e-01, -4.36089993e-01,
       -1.75894001e-01, -6.24897993e-01,  3.83323604e-01, -2.62635799e-01,
        4.22643995e-01,  

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('./datasets/text_cleaned.csv')
df.head(1)

Id   ProductId          UserId ProfileName  HelpfulnessNumerator  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW  delmartian                     1   

   HelpfulnessDenominator  Score        Time                Summary  \
0                       1      5  1303862400  Good Quality Dog Food   

                                                Text  label  \
0  I have bought several of the Vitality canned d...      1   

                                        text_cleaned  \
0  ['bought', 'several', 'vitality', 'canned', 'd...   

                                     lemmatized_text  
0  bought several vitality canned dog food produc...

In [8]:
"hELLO wORLD".split(' ')

['hELLO', 'wORLD']

In [9]:
df['vectorized_text'] = df['lemmatized_text'].apply(lambda tokens: vectorize_preprocessed_text(tokens.split(' '), glove_embeddings_100))

In [10]:
df.head(2)

Id   ProductId          UserId ProfileName  HelpfulnessNumerator  \
0   1  B001E4KFG0  A3SGXH7AUHU8GW  delmartian                     1   
1   2  B00813GRG4  A1D87F6ZCVE5NK      dll pa                     0   

   HelpfulnessDenominator  Score        Time                Summary  \
0                       1      5  1303862400  Good Quality Dog Food   
1                       0      1  1346976000      Not as Advertised   

                                                Text  label  \
0  I have bought several of the Vitality canned d...      1   
1  Product arrived labeled as Jumbo Salted Peanut...      0   

                                        text_cleaned  \
0  ['bought', 'several', 'vitality', 'canned', 'd...   
1  ['product', 'arrived', 'labeled', 'jumbo', 'sa...   

                                     lemmatized_text  \
0  bought several vitality canned dog food produc...   
1  product arrived labeled jumbo salted peanut .....   

                                     vectorized_text  
0  [-0.10477326755170469, 0.4299178531617616, 0.4...  
1  [-0.2240310903977264, 0.3681404632939534, 0.22...

In [11]:
df['vectorized_text'].shape

(393919,)

In [12]:
type(df['vectorized_text'])

pandas.core.series.Series

In [13]:
type(df['vectorized_text'].tolist())

list

In [14]:
x = np.array(df['vectorized_text'].values.tolist())
y = df['label'].values

In [15]:
print(x.shape, y.shape)

(393919, 100) (393919,)


## Data Split

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.17)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.22) # so 0.22 x 0.83 =~ 0.19 good 

## Logistic Regression

In [17]:
from sklearn.linear_model import LogisticRegression

logistic1 = LogisticRegression(solver='liblinear', max_iter=1000, penalty='l2')
logistic1.fit(X_train, y_train)

val_accuracy = logistic1.score(X_val, y_val)
print("Validation accuracy:", val_accuracy)

Validation accuracy: 0.8207979980536633


In [26]:
from sklearn.metrics import classification_report

y_pred = logistic1.predict(X_val)
report = classification_report(y_val, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.68      0.37      0.48     16001
           1       0.84      0.95      0.89     55929

    accuracy                           0.82     71930
   macro avg       0.76      0.66      0.69     71930
weighted avg       0.80      0.82      0.80     71930



In [18]:
# from sklearn.model_selection import GridSearchCV

# param_grid = {
#     'C': [0.001, 0.01, 0.1, 1, 10, 100],
#     'tol': [1e-3, 1e-4, 1e-5],
#     'penalty': ['l1', 'l2', 'elasticnet'],
#     'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
#     'max_iter': [200]
# }


# logistic_forGrid = LogisticRegression()
# logistic_grid_search = GridSearchCV(logistic_forGrid, param_grid, cv=5, scoring='accuracy', n_jobs=-1)

## Random Forest

In [27]:
from sklearn.ensemble import RandomForestClassifier

RFC1 = RandomForestClassifier(n_estimators=100)
RFC1.fit(X_train, y_train)

val_accuracy_RFC = RFC1.score(X_val, y_val)
print("RandomForestClassifier: Validation accuracy:", val_accuracy_RFC)

from sklearn.metrics import classification_report

y_pred = RFC1.predict(X_val)
report = classification_report(y_val, y_pred)
print(report)

RandomForestClassifier: Validation accuracy: 0.8028082858334492
              precision    recall  f1-score   support

           0       0.75      0.17      0.28     16001
           1       0.81      0.98      0.89     55929

    accuracy                           0.80     71930
   macro avg       0.78      0.58      0.58     71930
weighted avg       0.79      0.80      0.75     71930



## Cosine Similarity - KNN

In [28]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics.pairwise import cosine_distances

In [29]:
KNN = KNeighborsClassifier(n_neighbors=7, metric= 'precomputed')

In [30]:
cosine_dist_train = cosine_distances(X_train, X_train)
cosine_dist_train

MemoryError: Unable to allocate 485. GiB for an array with shape (255022, 255022) and data type float64

In [31]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.8)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.7) # so 0.32 x 0.6 =~ 0.24  

In [32]:
cosine_dist_train = cosine_distances(X_train, X_train)
cosine_dist_train

array([[0.        , 0.10614535, 0.09898691, ..., 0.12465802, 0.10094231,
        0.07316734],
       [0.10614535, 0.        , 0.11636677, ..., 0.05802315, 0.05676819,
        0.05852211],
       [0.09898691, 0.11636677, 0.        , ..., 0.10655886, 0.17360541,
        0.1199342 ],
       ...,
       [0.12465802, 0.05802315, 0.10655886, ..., 0.        , 0.11585894,
        0.08600499],
       [0.10094231, 0.05676819, 0.17360541, ..., 0.11585894, 0.        ,
        0.06156444],
       [0.07316734, 0.05852211, 0.1199342 , ..., 0.08600499, 0.06156444,
        0.        ]])

In [33]:
KNN.fit(cosine_dist_train, y_train)

KNeighborsClassifier(metric='precomputed', n_neighbors=7)

In [34]:
cosine_dist_test = cosine_distances(X_test, X_train)

MemoryError: Unable to allocate 55.5 GiB for an array with shape (315136, 23634) and data type float64

In [35]:
X_garbage, X_test, y_garbage, y_test = train_test_split(x, y, test_size=0.04)

In [36]:
cosine_dist_test = cosine_distances(X_test, X_train)

In [37]:
y_pred = KNN.predict(cosine_dist_test)

In [38]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7859364092149521
